#!/bin/bash
# File generated by Script (../genPowerSMT_FU_EXP2_by_QT_FU_2_chk_fexits.sh) at 13/06/2008-22:37:01.
# This script must be executed in /opt/simuladores/benchmarks/SPEC/SPEC2000/inputs-spec2000, because the inputs of inputs.

mkdir -p /home/rogerio/mestrado/pesquisa/simulacoes/resultados/powerSMT/dissertacao/FU_EXP2/20080613223701
cd /opt/simuladores/benchmarks/SPEC/SPEC2000/inputs-spec2000

